spring:
  datasource:
    primary:
      url: jdbc:mysql://47.92.225.99:3306/student?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
      username: root
      password: zyh19980604zyh
      driver-class-name: com.mysql.jdbc.Driver
---
server:
  port: 9658
spring:
  profiles: dev
---
spring:
  profiles:
    active: dev
---
